"""Type stubs for the cumem_utils pybind11 extension."""

def is_vmm_supported(device: int) -> bool: ...
def set_device(device: int) -> None: ...
def synchronize() -> None: ...
def enable_peer_access(device: int, peer: int) -> None: ...
def alloc_and_export_fd(size: int, device: int) -> tuple[int, int, int]: ...
def import_from_fd(fd: int, aligned_size: int, importer_device: int) -> int: ...
def free_local(ptr: int, aligned_size: int) -> None: ...
def close_imported(ptr: int, aligned_size: int) -> None: ...
def get_aligned_size(size: int, device: int) -> int: ...
