"""Type stubs for the ipc_utils pybind11 extension."""

def set_device(device: int) -> None: ...
def synchronize() -> None: ...
def get_device_count() -> int: ...
def alloc_and_export(size: int) -> tuple[int, bytes]: ...
def open_ipc(handle_bytes: bytes) -> int: ...
def close_ipc(ptr: int) -> None: ...
def free_buffer(ptr: int) -> None: ...
def create_event() -> int: ...
def record_event(evt: int) -> None: ...
def sync_event(evt: int) -> None: ...
def elapsed_ms(start: int, stop: int) -> float: ...
def destroy_event(evt: int) -> None: ...
